# Generated by Django 5.2.12 on 2026-03-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='提交内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='附件')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='teacher反馈')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('submitted', '已提交'), ('graded', '已评分')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
            ],
            options={
                'verbose_name': '任务提交',
                'verbose_name_plural': '任务提交',
                'db_table': 'task_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('due_date', models.DateTimeField(verbose_name='截止日期')),
                ('total_score', models.FloatField(default=100.0, verbose_name='总分')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'task',
                'ordering': ['due_date'],
            },
        ),
    ]
