# Generated by Django 5.2.12 on 2026-03-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='资源描述')),
                ('resource_type', models.CharField(choices=[('document', '文档'), ('video', '视频'), ('image', '图片'), ('archive', '压缩包'), ('other', '其他')], default='document', max_length=20, verbose_name='资源类型')),
                ('file', models.FileField(upload_to='resources/', verbose_name='文件')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
                'db_table': 'course_resource',
                'ordering': ['-created_at'],
            },
        ),
    ]
