# Generated by Django 5.2.10 on 2026-03-12 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_enrollment_options_and_more'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Resource', 'verbose_name_plural': 'Course Resources'},
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Resource Description'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(upload_to='resources/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='File Size (bytes)'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('image', 'Image'), ('archive', 'Archive'), ('other', 'Other')], default='document', max_length=20, verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Resource Title'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
    ]
