# Generated by Django 5.2.12 on 2026-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='课程代码')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('credits', models.IntegerField(default=0, verbose_name='学分')),
                ('semester', models.CharField(max_length=50, verbose_name='学期')),
                ('max_students', models.IntegerField(default=50, verbose_name='最大Student数')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='课程封面')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '在读'), ('completed', '已完成'), ('dropped', '已退课')], default='active', max_length=20, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '选课',
                'verbose_name_plural': '选课',
                'db_table': 'enrollment',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
